name: IDS20212
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21
  - scikit-learn=1.0
  - cartopy=0.20
  - pandas=1.3
  - matplotlib=3.5
  - seaborn=0.11
  - notebook=6.3
  - ipywidgets=7.6
  - nltk=3.5
  - plotly=5.4
  - gensim=4.0
  - ipympl=0.8
  - mlxtend=0.19
  - nb_conda
  - pip
  - pip:
    - pm4py==2.2.16
    - p-decision-tree
